### PR TITLE
Fixed Errors during compiling

### PR DESCRIPTION
**Pull request by jack-broadway**
Fixed warnings during the compilation of the kernel

### CODE REVIEW

**Comment by jack-broadway** [comment]
If you want me to explain it more I can

**Comment by DevriesL** [comment]
Hi,I did not see any compilation errors about this, can you tell me more details?

**Comment by jack-broadway** [comment]
Errors was probably the wrong word to use, they are actually warnings.

Compiler: SaberMod GCC 5.3 31/12
OS: Ubuntu 15.10 x64
Config: exynos7420-zerofltetw_defconfig

``` make
In file included from scripts/kconfig/zconf.tab.c:2503:0:
scripts/kconfig/menu.c: In function ‘get_symbol_str’:
scripts/kconfig/menu.c:567:18: warning: ‘jump’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     jump->offset = r->len - 1;
                  ^
scripts/kconfig/menu.c:528:19: note: ‘jump’ was declared here
  struct jump_key *jump;
                   ^
```

These occur near the start after running make

``` make
In file included from scripts/sortextable.c:166:0:
scripts/sortextable.c: In function ‘main’:
scripts/sortextable.h:158:3: warning: ‘relocs_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^
scripts/sortextable.h:104:6: note: ‘relocs_size’ was declared here
  int relocs_size;
      ^
In file included from scripts/sortextable.c:164:0:
scripts/sortextable.h:158:3: warning: ‘relocs_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   memset(relocs, 0, relocs_size);
   ^
scripts/sortextable.h:104:6: note: ‘relocs_size’ was declared here
  int relocs_size;
      ^
```

This is in the final steps of compilation

``` make
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_fmp_utils.c: In function ‘main’:
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_fmp_utils.c:24:7: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
  if (!strcmp("-u", argv[1])) {
       ^
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_fmp_utils.c:46:10: warning: implicit declaration of function ‘update_fmp_hmac’ [-Wimplicit-function-declaration]
   return update_fmp_hmac(vmlinux_file, hmac_file, offset);
          ^
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_fmp_utils.c:73:10: warning: implicit declaration of function ‘collect_fmp_bytes’ [-Wimplicit-function-declaration]
   return collect_fmp_bytes(in_file, section_name, offset, size, out_file);
          ^
HMAC-SHA256(builtime_bytes.bin)= 329173eb139263c7e7358c9b9cbc7a0710d285af18e3084a3c5b12f9118dd60b
  FIPS : Generating hmac of crypto and updating vmlinux... 
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_crypto_utils.c: In function ‘main’:
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_crypto_utils.c:29:7: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
  if (!strcmp ("-u", argv[1]))
       ^
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_crypto_utils.c:53:10: warning: implicit declaration of function ‘update_crypto_hmac’ [-Wimplicit-function-declaration]
   return update_crypto_hmac (vmlinux_file, hmac_file, offset);
          ^
/home/jack/KernelTest/SM-G9208_ImageBreaker/scripts/fips_crypto_utils.c:83:10: warning: implicit declaration of function ‘collect_crypto_bytes’ [-Wimplicit-function-declaration]
   return collect_crypto_bytes (in_file, section_name, offset, size, out_file);
          ^
```

So while its not necessary to fix them, cleaner build output is always nice?

**Comment by DevriesL** [comment]
OK，thanks for your work，so you also have a SM-G9208 and test these commit?

**Comment by jack-broadway** [comment]
I didnt use the mkbootimg_tools to build it as im packaging the kernel with Kali nethunter, I used the nethunter build tools in kernel only mode to build a flashable zip. So if you want me to build with mkbootimg_tools I can check for you, although I dont know how to use them.

**Pull request closed without merging**
